"""
Django settings for core project

Generated by 'django-admin startproject' using Django 4.1.2

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from str2bool import str2bool

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

DEFAULT_SECRET_KEY = "Super_Secr3t_9999"


def _get_csv_env(name):
    """
    Return one comma-separated environment variable as a clean list
    """
    return [
        value.strip()
        for value in os.getenv(name, "").split(",")
        if value.strip()
    ]


def _get_required_production_secret_key():
    """
    Return the configured production secret key
    """
    secret_key = os.getenv("SECRET_KEY", DEFAULT_SECRET_KEY)
    if not secret_key or secret_key == DEFAULT_SECRET_KEY:
        raise ImproperlyConfigured(
            "Production SECRET_KEY must be set to a non-default value"
        )
    return secret_key


def _get_production_database_settings():
    """
    Return the configured production database settings
    """
    required_names = (
        "DB_ENGINE",
        "DB_NAME",
        "DB_USERNAME",
        "DB_PASS",
        "DB_HOST",
        "DB_PORT",
    )
    values = {
        name: os.getenv(name, "").strip()
        for name in required_names
    }
    missing_names = [
        name
        for name, value in values.items()
        if not value
    ]
    if missing_names:
        raise ImproperlyConfigured(
            "Missing production database setting(s): "
            + ", ".join(missing_names)
        )
    if values["DB_ENGINE"] != "postgresql":
        raise ImproperlyConfigured(
            "Production database engine must be postgresql"
        )
    return {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": values["DB_NAME"],
            "USER": values["DB_USERNAME"],
            "PASSWORD": values["DB_PASS"],
            "HOST": values["DB_HOST"],
            "PORT": values["DB_PORT"],
            "OPTIONS": {"sslmode": "require"},
            "CONN_MAX_AGE": 60,
            "CONN_HEALTH_CHECKS": True,
        }
    }


# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = str2bool(os.getenv("DEBUG", "False"))
SECRET_KEY = (
    os.getenv("SECRET_KEY", DEFAULT_SECRET_KEY)
    if DEBUG
    else _get_required_production_secret_key()
)

LOCAL_ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]
LOCAL_CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5085",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:5085",
]

if DEBUG:
    ALLOWED_HOSTS = LOCAL_ALLOWED_HOSTS + _get_csv_env("ALLOWED_HOSTS")
    CSRF_TRUSTED_ORIGINS = LOCAL_CSRF_TRUSTED_ORIGINS + _get_csv_env(
        "CSRF_TRUSTED_ORIGINS"
    )
else:
    ALLOWED_HOSTS = _get_csv_env("ALLOWED_HOSTS")
    CSRF_TRUSTED_ORIGINS = _get_csv_env("CSRF_TRUSTED_ORIGINS")

RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 8 * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
TRUSTED_PROXY_HOPS = int(os.getenv("TRUSTED_PROXY_HOPS", "1" if not DEBUG else "0"))

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    'admin_datta.apps.AdminDattaConfig',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Serve UI pages
    "apps.pages",

    # Dynamic DT
    "apps.dyn_dt",

    # Dynamic API
    "apps.dyn_api",

    # Charts
    "apps.charts",

    # Tooling API-GEN
    'rest_framework',            # Include DRF           # <-- NEW 
    'rest_framework.authtoken',  # Include DRF Auth      # <-- NEW     
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.pages.session_policy.LoginSessionExpiryMiddleware",
    "apps.pages.middleware.ORCIDAccountSetupMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates') 

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.pages.context_processors.shared_data_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = _get_production_database_settings()

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

#if not DEBUG:
#    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/search/"
LOGIN_URL = "/login/"
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

PILOT_RATE_LIMITS = {
    "registration": {"limit": 5, "window_seconds": 3600},
    "credential_validation": {"limit": 120, "window_seconds": 60},
    "password_login": {"limit": 10, "window_seconds": 900},
    "orcid_start": {"limit": 20, "window_seconds": 3600},
    "upload": {"limit": 20, "window_seconds": 3600},
}
PILOT_MAX_UPLOAD_FILES = 5
PILOT_MAX_UPLOAD_FILE_BYTES = 10 * 1024 * 1024
PILOT_MAX_UPLOAD_REQUEST_BYTES = 25 * 1024 * 1024
PILOT_MAX_UPLOAD_OBJECTS = 100
PILOT_MAX_JSON_DEPTH = 100
PILOT_MAX_USER_JSON_BYTES = 50 * 1024 * 1024

ORCID_BASE_URL = os.environ.get("ORCID_BASE_URL", "https://sandbox.orcid.org").rstrip("/")
ORCID_CLIENT_ID = os.environ.get("ORCID_CLIENT_ID", "")
ORCID_CLIENT_SECRET = os.environ.get("ORCID_CLIENT_SECRET", "")
ORCID_REDIRECT_URI = os.environ.get("ORCID_REDIRECT_URI", "")

# ### DYNAMIC_DATATB Settings ###
DYNAMIC_DATATB = {
    # SLUG -> Import_PATH 
    'product'  : "apps.pages.models.Product",
}
########################################

# Syntax: URI -> Import_PATH
DYNAMIC_API = {
    # SLUG -> Import_PATH 
    'product'  : "apps.pages.models.Product",
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}
########################################
