# Generated by Codex on 2026-05-19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0002_jsondata"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsondata",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_json_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
