# Generated by Django 4.2.9 on 2026-06-30 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_jsondata_shared_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='shared_data', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_data_notifications', to=settings.AUTH_USER_MODEL)),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pages.jsondata')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_read', '-created_at'),
            },
        ),
    ]
