# Generated by Codex on 2026-06-30

from django.db import migrations


def create_existing_share_notifications(apps, schema_editor):
    """
    Create notifications for existing private shared data objects
    """
    JSONData = apps.get_model("pages", "JSONData")
    DataNotification = apps.get_model("pages", "DataNotification")

    notifications = []
    data_objects = (
        JSONData.objects
        .filter(access_type="c")
        .select_related("owner")
        .prefetch_related("shared_users")
    )

    for data_object in data_objects:
        data = data_object.data or {}
        if isinstance(data, dict):
            title = data.get("identifier") or data.get("title") or "Data object"
        else:
            title = "Data object"

        title = str(title)[:180]

        for recipient in data_object.shared_users.all():
            if recipient.pk == data_object.owner_id:
                continue

            exists = DataNotification.objects.filter(
                recipient_id=recipient.pk,
                actor_id=data_object.owner_id,
                data_object_id=data_object.pk,
                notification_type="shared_data",
            ).exists()

            if exists:
                continue

            notifications.append(
                DataNotification(
                    recipient_id=recipient.pk,
                    actor_id=data_object.owner_id,
                    data_object_id=data_object.pk,
                    notification_type="shared_data",
                    message=f"{data_object.owner.username} shared {title} with you.",
                )
            )

    if notifications:
        DataNotification.objects.bulk_create(notifications)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_datanotification"),
    ]

    operations = [
        migrations.RunPython(create_existing_share_notifications, migrations.RunPython.noop),
    ]
