# Generated by Codex on 2026-08-09

import json

from django.db import migrations, models


def backfill_jsondata_size_bytes(apps, schema_editor):
    """
    Backfill compact UTF-8 byte sizes for existing JSONData rows
    """
    db_alias = schema_editor.connection.alias
    json_data_model = apps.get_model("pages", "JSONData")

    for json_data in json_data_model.objects.using(db_alias).all().iterator():
        payload = json.dumps(
            json_data.data,
            ensure_ascii=False,
            separators=(",", ":"),
        ).encode("utf-8")
        json_data.size_bytes = len(payload)
        json_data.save(using=db_alias, update_fields=["size_bytes"])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_accountprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsondata",
            name="size_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=32)),
                ("identifier_hash", models.CharField(max_length=64)),
                ("window_seconds", models.PositiveIntegerField()),
                ("window_id", models.BigIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "scope",
                            "identifier_hash",
                            "window_seconds",
                            "window_id",
                        ),
                        name="unique_rate_limit_bucket",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_jsondata_size_bytes,
            migrations.RunPython.noop,
        ),
    ]
