# Generated by Django 5.2.16 on 2026-09-23 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_accountprofile_research_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadWorkerInstance',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('heartbeat_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField()),
                ('instance_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('ready', models.BooleanField(default=False)),
                ('claim_token', models.UUIDField(editable=False, null=True)),
                ('files', models.JSONField(default=list)),
                ('staged_bytes', models.PositiveBigIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('level', models.CharField(default='info', max_length=10)),
                ('report_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'submission_id'), name='unique_owner_upload_submission')],
            },
        ),
    ]
