# Generated by Django 5.2.16 on 2026-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_upload_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='identifier_lookup',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64),
        ),
    ]
